// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Song } from "./Song";

export type Album = { songs: Array<Song>, id: number, 
/**
 * The name of the song
 */
title: string, 
/**
 * The creator of the song
 */
artist: string, cover: string | null, 
/**
 * A unix timestamp of when this song was added
 */
created_at: number, };
