// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioMetadata = { id: number, url: string, webpage_url: string | null, title: string, artist: string | null, album: string | null, thumbnail: string | null, duration: number | null, };
