// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The definition of a song.
 */
export type AudioFile = { id: number, file_name: string, file_path: string, duration: number, 
/**
 * A unix timestamp of when this song was added
 */
created_at: number, };
