// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioMetadata } from "./AudioMetadata";
import type { State } from "./State";

export type BotData = { name: string, state: State, volume: number, position: number | null, currently_playing: AudioMetadata | null, playlist: Array<AudioMetadata>, };
