// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The definition of a favourite
 */
export type Favourite = { id: number, 
/**
 * The favourited song
 */
song_id: number, 
/**
 * A unix timestamp of when this song was added
 */
created_at: number, };
