// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PutSongMetadata = { track: number | null, title: string, artist: string, album: string | null, disc_number: number | null, cover_path: string | null, };
