// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PutState = { playing: boolean | null, volume: number | null, seek: number | null, next: boolean, };
