// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SongMetadata = { track: number | null, title: string | null, artist: string | null, album: string | null, cover_path: string | null, 
/**
 * The duration of the song in milliseconds
 */
duration: number, };
