// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The definition of a song.
 */
export type Song = { id: number, 
/**
 * The id of the song within the album
 */
track: number | null, 
/**
 * The name of the song
 */
title: string, 
/**
 * The creator of the song
 */
artist: string, 
/**
 * The creator of the song
 */
album: string | null, 
/**
 * The disc of the album
 */
disc_number: number | null, file_id: number, favourite_count: number, 
/**
 * A unix timestamp of when this song was added
 */
created_at: number, };
