// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SongMetadata } from "./SongMetadata";

export type UploadResponse = { file_id: number, metadata: SongMetadata, };
